### ISSUE TITLE
网站上传后无反应

### ISSUE THREAD

**Issue by navfour** [chocoiii/ODKG#1]
您好，感谢您的项目。但是我们在尝试访问网站demo的时候，在上传zip/txt文件后下方并没有出现说明文档中的可选项。

**Comment by chocoiii** [comment]
您好，问题以及解决，网站现在可以正常使用。

**Comment by chocoiii** [comment]
感谢你的建议，由于是我们租用的阿里云带宽过小，导致部署后的各项功能存在不稳定现象，需要定期清除云服务器上的缓存，目前网站现在可以正常使用。
